(() => {
const m=window.MAGAZINE,book=document.querySelector('#book');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=s=>s.replace(/\n/g,''),title=s=>esc(s).replace(/\n/g,'<br>');
const footer=n=>`<footer class="folio"><span>${String(n).padStart(2,'0')} <b>|</b> 科研树er · 材料新生</span><span>01 / 2026</span></footer>`;
const head=label=>`<div class="running-head"><span>${esc(label)}</span><span>RESEARCH IN MATERIALS</span></div>`;
const paragraph=(a,n)=>`<p>${esc(a.paragraphs[n])}</p>`;
function figure(a,secondary=false){const f=secondary?a.secondary:{image:a.image,imageAlt:a.imageAlt,caption:a.caption,captionEnglish:a.captionEnglish};return `<figure><a class="figure-link" href="${esc(f.image)}" target="_blank" rel="noopener" aria-label="查看研究配图大图（新标签页）"><img src="${esc(f.image)}" alt="${esc(f.imageAlt)}"></a><figcaption>${esc(f.caption)}${f.captionEnglish?`<span lang="en">${esc(f.captionEnglish)}</span>`:''}</figcaption></figure>`;}
const metrics=a=>`<div class="data-points">${a.metrics.map(([v,u,l])=>`<div><strong>${esc(v)}<small>${esc(u)}</small></strong><span>${esc(l)}</span></div>`).join('')}</div>`;
const insight=a=>`<aside class="insight"><h3>研究启示</h3><p>${esc(a.takeaway)}</p></aside>`;
const publication=a=>a.publication?`<aside class="publication-note"><p>该研究于 ${esc(a.publication.year)} 年发表于《${esc(a.journal)}》，论文题为《${esc(a.publication.title)}》（中文译名）。论文已上线，可在线阅读。</p><a href="https://doi.org/${esc(a.doi)}" target="_blank" rel="noopener noreferrer">阅读论文原文 ↗</a></aside>`:'';
const source=a=>`<div class="source-row"><span>${esc(a.institution)} · <em>${esc(a.journal)}</em></span><a href="${a.source}" target="_blank" rel="noopener noreferrer">公众号原文 ↗</a></div>`;
function composition(a){
 if(a.layout==='alternating-media')return `<div class="article-layout alternating"><div class="upper-zone"><div class="copy">${paragraph(a,0)}</div>${figure(a)}</div><div class="lower-zone">${figure(a,true)}<div class="copy">${paragraph(a,1)}${metrics(a)}${insight(a)}</div></div></div>`;
 if(a.layout==='diagram-first')return `<div class="article-layout diagram-first">${figure(a)}<div class="three-columns"><div class="copy">${paragraph(a,0)}</div><div class="copy">${paragraph(a,1)}</div><div class="copy">${publication(a)}${insight(a)}</div></div></div>`;
 if(a.layout==='feature-band')return `<div class="article-layout feature-band">${figure(a)}<div class="feature-bottom"><div class="copy">${paragraph(a,0)}${paragraph(a,1)}</div><div class="feature-aside">${publication(a)}${insight(a)}</div></div></div>`;
 if(a.layout==='lead-side-image')return `<div class="article-layout lead-side"><div class="copy narrative"><h3>从废物到功能位点</h3>${paragraph(a,0)}<h3>吸附与分子识别</h3>${paragraph(a,1)}${insight(a)}</div><div class="figure-stack">${figure(a)}${figure(a,true)}</div>${metrics(a)}</div>`;
 return `<div class="article-layout solar-zones"><div class="solar-top"><div class="copy"><h3>01 / 把光留在界面</h3>${paragraph(a,0)}</div>${figure(a)}</div><div class="solar-bottom">${figure(a,true)}<div class="copy"><h3>02 / 让水更易蒸发</h3>${paragraph(a,1)}${metrics(a)}</div></div>${insight(a)}</div>`;
}
const cover=`<section class="page cover" data-density="hard" aria-label="第 1 页 封面"><div class="page-inner"><div class="cover-masthead"><span>科研树er</span><span>RESEARCH<br>IN MATERIALS</span></div><div class="cover-heading"><p>材料创新 / 研究导读</p><h1>${esc(m.title)}</h1><span>${esc(m.subtitle)}</span></div><div class="cover-art"><img src="assets/material-lattice.svg" alt="原创材料孔道结构艺术插图，非实验图"><span>STRUCTURE.<br>FUNCTION.<br>FUTURE.</span></div><div class="cover-summary"><div><small>本期精选</small><p>天然结构的功能觉醒<br>废弃物的循环旅程<br>生物炭的界面设计</p></div><div class="cover-issue">01<small>2026 / 10</small></div></div><div class="cover-foot">五篇科研导读 · 精选样刊<span>以图读文，捕捉灵感</span></div></div></section>`;
const contents=`<section class="page contents" aria-label="第 2 页 目录"><div class="page-inner">${head('CONTENTS / 目录')}<div class="contents-heading"><h2>本期目录</h2><p>从天然结构，到循环未来。</p></div><div class="contents-list">${m.articles.map(a=>`<button data-page="${a.page}" class="contents-item"><img src="${esc(a.image)}" alt=""><span class="contents-text"><small>${String(a.page).padStart(2,'0')} / ${esc(a.category)}</small><strong>${esc(plain(a.title))}</strong><span>${esc(a.deck)}</span></span><span class="toc-arrow" aria-hidden="true">↗</span></button>`).join('')}</div><div class="publication-strip"><strong>科研树er / MATERIALS</strong><p>五篇精选研究 · 中文编辑导读<br>完整实验条件与文献请见各页原文。</p></div>${footer(2)}</div></section>`;
const articles=m.articles.map(a=>`<article class="page article layout-${a.layout}" aria-label="第 ${a.page} 页 ${esc(plain(a.title))}"><div class="page-inner">${head(`${a.category} / ${a.english}`)}<div class="article-heading"><h2>${title(a.title)}</h2><p class="deck">${esc(a.deck)}</p></div>${composition(a)}${source(a)}${footer(a.page)}</div></article>`).join('');
const back=`<section class="page back-cover" data-density="hard" aria-label="第 8 页 封底"><div class="page-inner">${head('UNTIL NEXT TIME')}<div class="back-logo">树<span>er</span></div><span class="back-kicker">IDEAS GROW HERE</span><h2>让科研灵感，<br>继续生长。</h2><p class="back-deck">读懂材料。连接思路。<br>发现下一种可能。</p><div class="back-rule"></div><div class="back-colophon"><h3>内容来源</h3><p>微信公众号「科研树er」<br>五篇材料研究 · 中文编辑导读</p><h3>本刊信息</h3><p>2026 年 10 月 / 第 01 期 / 共 8 页<br>材料科学专题 · 研究图解与前沿导读。</p><p class="rights">导读标题经编辑提炼。研究图片及原文权利归各原作者或权利人所有；封面为原创结构插图。本样刊不代表公众号官方出版物。</p></div><button class="back-to-start" data-page="1">重新翻阅 ↗</button>${footer(8)}</div></section>`;
book.innerHTML=cover+contents+articles+back;
document.querySelector('.reader-heading').innerHTML='<span class="eyebrow">THE MATERIALS ISSUE / 01</span><div class="reader-tools"><span class="reading-mode" id="reading-mode">双页阅读</span><button id="read-open" class="read-open">放大阅读 ↗</button></div>';
const flip=new St.PageFlip(book,{width:540,height:765,size:'stretch',minWidth:280,maxWidth:540,minHeight:397,maxHeight:765,showCover:true,usePortrait:true,autoSize:false,drawShadow:true,maxShadowOpacity:.2,flippingTime:matchMedia('(prefers-reduced-motion: reduce)').matches?1:650,mobileScrollSupport:true,swipeDistance:30,clickEventForward:true});
window.magazineFlip=flip;
const prev=document.querySelector('#prev'),next=document.querySelector('#next'),select=document.querySelector('#page-select'),dialog=document.querySelector('#toc-dialog'),readDialog=document.querySelector('#read-dialog');
const entries=[['封面',1],['目录',2],...m.articles.map(a=>[plain(a.title),a.page]),['封底',8]];
select.innerHTML=entries.map(([,p])=>`<option value="${p}">${String(p).padStart(2,'0')}</option>`).join('');
document.querySelector('#toc-list').innerHTML=entries.map(([n,p])=>`<button class="dialog-entry" data-page="${p}"><span>${String(p).padStart(2,'0')}</span><strong>${esc(n)}</strong><span>↗</span></button>`).join('');
function update(){const i=flip.getCurrentPageIndex(),portrait=flip.getOrientation()==='portrait';let range=String(i+1);if(!portrait&&i>0&&i<7)range+=`–${i+2}`;document.querySelector('#page-status').textContent=`第 ${range} 页 / 共 8 页`;document.querySelector('#stage').classList.toggle('single-front',!portrait&&i===0);document.querySelector('#stage').classList.toggle('single-back',!portrait&&i===7);select.value=i+1;prev.disabled=i===0;next.disabled=i===7;document.querySelector('#reading-mode').textContent=portrait?'单页阅读':'双页阅读';}
flip.on('flip',update);flip.on('changeOrientation',update);flip.on('init',update);flip.loadFromHTML(document.querySelectorAll('.page'));
prev.onclick=()=>flip.flipPrev();next.onclick=()=>flip.flipNext();select.onchange=()=>flip.turnToPage(Number(select.value)-1);
document.addEventListener('click',e=>{const el=e.target.closest('[data-page]');if(el){flip.turnToPage(Number(el.dataset.page)-1);if(dialog.open)dialog.close();if(readDialog.open)readDialog.close();}});
document.querySelector('#toc-open').onclick=()=>dialog.showModal();document.querySelector('#toc-close').onclick=()=>dialog.close();document.querySelector('#read-close').onclick=()=>readDialog.close();
document.querySelector('#read-open').onclick=()=>{const i=flip.getCurrentPageIndex(),pages=[i+1];if(flip.getOrientation()==='landscape'&&i>0&&i<7)pages.push(i+2);const selected=m.articles.filter(a=>pages.includes(a.page));document.querySelector('#read-content').innerHTML=selected.length?selected.map(a=>`<article class="reading-article"><small>${esc(a.category)} / ${a.english}</small><h2>${esc(plain(a.title))}</h2><p class="reading-deck">${esc(a.deck)}</p>${paragraph(a,0)}${figure(a)}${paragraph(a,1)}${a.secondary?figure(a,true):''}${metrics(a)}${publication(a)}${insight(a)}${source(a)}</article>`).join(''):`<article class="reading-article"><small>科研树er · 第 01 期</small><h2>${esc(m.title)}</h2><p>本刊根据「科研树er」五篇文章编排为中文导读。选择文章开始阅读。</p>${m.articles.map(a=>`<button class="reading-link" data-page="${a.page}">${String(a.page).padStart(2,'0')} / ${esc(plain(a.title))} ↗</button>`).join('')}</article>`;readDialog.showModal();readDialog.scrollTop=0;};
for(const d of [dialog,readDialog])d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});
document.addEventListener('keydown',e=>{if(dialog.open||readDialog.open||e.ctrlKey||e.metaKey||e.altKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();flip.flipNext();}if(e.key==='ArrowLeft'){e.preventDefault();flip.flipPrev();}if(e.key==='Home'){e.preventDefault();flip.turnToPage(0);}if(e.key==='End'){e.preventDefault();flip.turnToPage(7);}});update();
})();


